'use client';
import Image from 'next/image';
import { useEffect, useState, type FormEvent } from 'react';
import { LogOut, LockKeyhole, Ticket } from 'lucide-react';
import { getSupabase, friendlyError } from '@/lib/supabase';
import { Button, Field } from './ui';
import { ClubWorkspace } from './club-workspace';
import type { ClubActor } from '@/lib/club';
import s from './club.module.css';

export function ClubPortal(){
 const supabase=getSupabase(); const[ready,setReady]=useState(false); const[actor,setActor]=useState<ClubActor|null>(null);
 const[email,setEmail]=useState(''),[password,setPassword]=useState(''); const[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let active=true;async function resolve(){if(!supabase){if(active)setReady(true);return}const session=await supabase.auth.getSession();if(!active)return;if(!session.data.session){setActor(null);setReady(true);return}try{const response=await fetch('/api/club?me=1',{cache:'no-store',headers:{Authorization:`Bearer ${session.data.session.access_token}`}});if(!active)return;if(!response.ok){await supabase.auth.signOut();setActor(null);setError('Este usuário não está cadastrado ou ativo no Clube TLU.')}else setActor(await response.json())}catch{if(active)setError('Não foi possível validar seu acesso ao Clube TLU.')}finally{if(active)setReady(true)}}void resolve();const{data}=supabase?.auth.onAuthStateChange((_event,session)=>{if(!session&&active){setActor(null);setReady(true)}})||{data:null};return()=>{active=false;data?.subscription.unsubscribe()}},[supabase]);
 async function login(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!supabase)return;setBusy(true);setError('');try{const result=await supabase.auth.signInWithPassword({email:email.trim().toLowerCase(),password});if(result.error)throw result.error;const response=await fetch('/api/club?me=1',{cache:'no-store',headers:{Authorization:`Bearer ${result.data.session.access_token}`}});if(!response.ok){await supabase.auth.signOut();setActor(null);setError('Login válido, mas este usuário não está cadastrado e ativo no Clube TLU.');return}setActor(await response.json());setPassword('')}catch(cause){setError(friendlyError(cause))}finally{setBusy(false);setReady(true)}}
 async function logout(){setBusy(true);try{await supabase?.auth.signOut();setActor(null);setError('')}finally{setBusy(false)}}
 return <main className={s.portal}><header className={s.portalHeader}><div className={s.brand}><Image src="/logo-terra-lotus.png" alt="Terra Lótus Urbanismo" width={160} height={60} priority/><span>Clube TLU</span></div>{actor?<div className={s.actions}><span className={s.roleChip}>{actor.role==='partner'?'Parceiro':actor.role==='client'?'Cliente':'Gestão TLU'}</span><Button variant="secondary" disabled={busy} onClick={()=>void logout()}><LogOut size={16}/>Sair</Button></div>:null}</header>
 {!ready?<div className={s.empty}>Preparando seu acesso…</div>:!supabase?<div className={s.empty}><h1>Clube temporariamente indisponível</h1><p>Entre em contato com a equipe TLU.</p></div>:actor?<ClubWorkspace external/>:<section className={s.login}><div className={s.loginIntro}><span className={s.icon}><Ticket size={28}/></span><span className={s.eyebrow}>Clube de benefícios</span><h1>Seu acesso. Sua experiência.</h1><p>Clientes encontram benefícios e seus cupons. Parceiros administram descontos e validam utilizações. A visão é definida pelo cadastro feito pela TLU.</p><div className={s.steps}><span>Cliente · benefícios e meus cupons</span><span>Parceiro · descontos e validação</span><span>Acesso somente para usuários cadastrados</span></div></div><form className={s.loginCard} onSubmit={login}><LockKeyhole size={25}/><h2>Entrar no Clube TLU</h2><p>Use o e-mail e a senha definidos no seu cadastro do clube.</p><Field label="E-mail"><input type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} maxLength={254} required/></Field><Field label="Senha"><input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} minLength={12} maxLength={128} required/></Field>{error?<p className={s.error} role="alert">{error}</p>:null}<Button type="submit" disabled={busy} loading={busy}>Entrar</Button><small>Não há cadastro público. A Terra Lótus precisa cadastrar seu perfil como cliente ou parceiro antes do primeiro acesso.</small></form></section>}</main>
}
